/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/droide.glb -o app/components/Droid.tsx --types --root public/ 
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-droide-de-seguridad-k-2so-by-oscar-creativo-e4c65688ae1b47ec9e1dd6acec2dcadd
Title: Free Droide De Seguridad K-2SO By Oscar Creativo
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'motion'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
    New_MMD_Model_03: THREE.Bone
    origin_04: THREE.Bone
    hip_05: THREE.Bone
    l_thigh_06: THREE.Bone
    l_knee_07: THREE.Bone
    l_ankle_08: THREE.Bone
    l_ball_09: THREE.Bone
    l_toe_010: THREE.Bone
    l_knee_segment_1_011: THREE.Bone
    l_knee_segment_2_012: THREE.Bone
    l_knee_segment_3_013: THREE.Bone
    l_knee_segment_4_014: THREE.Bone
    l_knee_segment_5_015: THREE.Bone
    l_thigh_segment_1_016: THREE.Bone
    l_thigh_segment_2_017: THREE.Bone
    l_thigh_segment_3_018: THREE.Bone
    l_thigh_segment_4_019: THREE.Bone
    l_thigh_segment_5_020: THREE.Bone
    spineA_021: THREE.Bone
    spineB_022: THREE.Bone
    spineC_023: THREE.Bone
    spineD_024: THREE.Bone
    spineE_025: THREE.Bone
    spineF_026: THREE.Bone
    neckA_027: THREE.Bone
    neckB_028: THREE.Bone
    head_029: THREE.Bone
    head_tip_030: THREE.Bone
    l_eye_031: THREE.Bone
    r_eye_032: THREE.Bone
    l_clav_033: THREE.Bone
    l_shoulder_034: THREE.Bone
    l_elbow_035: THREE.Bone
    l_elbow_segment_5_036: THREE.Bone
    l_wrist_037: THREE.Bone
    l_wristEnd_038: THREE.Bone
    l_finThumbA_039: THREE.Bone
    l_finThumbB_040: THREE.Bone
    l_finThumbC_041: THREE.Bone
    l_finThumbCEnd_042: THREE.Bone
    l_finIndexCarpal_043: THREE.Bone
    l_finIndexA_044: THREE.Bone
    l_finIndexB_045: THREE.Bone
    l_finIndexC_046: THREE.Bone
    l_finIndexCEnd_047: THREE.Bone
    l_finMidCarpal_048: THREE.Bone
    l_finMidA_049: THREE.Bone
    l_finMidB_050: THREE.Bone
    l_finMidC_051: THREE.Bone
    l_finMidCEnd_052: THREE.Bone
    l_finRingCarpal_053: THREE.Bone
    l_finRingA_054: THREE.Bone
    l_finRingB_055: THREE.Bone
    l_finRingC_056: THREE.Bone
    l_finRingCEnd_057: THREE.Bone
    l_finPinkyCarpal_058: THREE.Bone
    l_finPinkyA_059: THREE.Bone
    l_finPinkyB_060: THREE.Bone
    l_finPinkyC_061: THREE.Bone
    l_finPinkyCEnd_062: THREE.Bone
    l_shoulder_segment_1_063: THREE.Bone
    l_shoulder_segment_3_064: THREE.Bone
    l_shoulder_segment_5_065: THREE.Bone
    l_shoulderPad_066: THREE.Bone
    r_clav_067: THREE.Bone
    r_shoulder_068: THREE.Bone
    r_elbow_069: THREE.Bone
    r_wrist_070: THREE.Bone
    r_wristEnd_071: THREE.Bone
    r_finThumbA_072: THREE.Bone
    r_finThumbB_073: THREE.Bone
    r_finThumbC_074: THREE.Bone
    r_finThumbCEnd_00: THREE.Bone
    r_finIndexCarpal_01: THREE.Bone
    r_finIndexA_075: THREE.Bone
    r_finIndexB_076: THREE.Bone
    r_finIndexC_077: THREE.Bone
    r_finIndexCEnd_078: THREE.Bone
    r_finMidCarpal_079: THREE.Bone
    r_finMidA_080: THREE.Bone
    r_finMidB_081: THREE.Bone
    r_finMidC_082: THREE.Bone
    r_finMidCEnd_083: THREE.Bone
    r_finRingCarpal_084: THREE.Bone
    r_finRingA_085: THREE.Bone
    r_finRingB_086: THREE.Bone
    r_finRingC_087: THREE.Bone
    r_finRingCEnd_088: THREE.Bone
    r_finPinkyCarpal_089: THREE.Bone
    r_finPinkyA_090: THREE.Bone
    r_finPinkyB_091: THREE.Bone
    r_finPinkyC_092: THREE.Bone
    r_finPinkyCEnd_093: THREE.Bone
    r_elbow_segment_5_094: THREE.Bone
    r_shoulder_segment_1_095: THREE.Bone
    r_shoulder_segment_3_096: THREE.Bone
    r_shoulder_segment_5_097: THREE.Bone
    r_shoulderPad_098: THREE.Bone
    l_shoulderPiston_A_099: THREE.Bone
    l_shoulderPiston_B_0100: THREE.Bone
    l_shoulderPiston_C_0101: THREE.Bone
    l_shoulderPiston_D_0102: THREE.Bone
    l_shoulderPiston_E_0103: THREE.Bone
    l_shoulderPiston_F_0104: THREE.Bone
    l_shoulderPiston_G_0105: THREE.Bone
    l_shoulderPiston_H_0106: THREE.Bone
    l_shoulderPiston_I_0107: THREE.Bone
    l_shoulderPiston_J_0108: THREE.Bone
    l_shoulderPiston_K_0109: THREE.Bone
    l_shoulderPiston_L_0110: THREE.Bone
    l_shoulderPiston_M_0111: THREE.Bone
    l_shoulderPiston_N_0112: THREE.Bone
    l_shoulderPiston_O_0113: THREE.Bone
    l_shoulderPiston_P_0114: THREE.Bone
    r_shoulderPiston_A_0115: THREE.Bone
    r_shoulderPiston_B_0116: THREE.Bone
    r_shoulderPiston_C_0117: THREE.Bone
    r_shoulderPiston_D_0118: THREE.Bone
    r_shoulderPiston_E_0119: THREE.Bone
    r_shoulderPiston_F_0120: THREE.Bone
    r_shoulderPiston_G_0121: THREE.Bone
    r_shoulderPiston_H_0122: THREE.Bone
    r_shoulderPiston_I_0123: THREE.Bone
    r_shoulderPiston_J_0124: THREE.Bone
    r_shoulderPiston_K_0125: THREE.Bone
    r_shoulderPiston_L_0126: THREE.Bone
    r_shoulderPiston_M_0127: THREE.Bone
    r_shoulderPiston_N_0128: THREE.Bone
    r_shoulderPiston_O_0129: THREE.Bone
    r_shoulderPiston_P_0130: THREE.Bone
    r_thigh_0131: THREE.Bone
    r_knee_0132: THREE.Bone
    r_ankle_0133: THREE.Bone
    r_ball_0134: THREE.Bone
    r_toe_0135: THREE.Bone
    r_knee_segment_1_0136: THREE.Bone
    r_knee_segment_2_0137: THREE.Bone
    r_knee_segment_3_0138: THREE.Bone
    r_knee_segment_4_0139: THREE.Bone
    r_knee_segment_5_0140: THREE.Bone
    r_thigh_segment_1_0141: THREE.Bone
    r_thigh_segment_2_0142: THREE.Bone
    r_thigh_segment_3_0143: THREE.Bone
    r_thigh_segment_4_0144: THREE.Bone
    r_thigh_segment_5_0145: THREE.Bone
    l_hipPiston_A_0146: THREE.Bone
    l_hipPiston_B_0147: THREE.Bone
    l_hipPiston_C_0148: THREE.Bone
    l_hipPiston_D_0149: THREE.Bone
    l_hipPiston_E_0150: THREE.Bone
    l_hipPiston_F_0151: THREE.Bone
    l_hipPiston_G_0152: THREE.Bone
    l_hipPiston_H_0153: THREE.Bone
    l_hipPiston_I_0154: THREE.Bone
    l_hipPiston_J_0155: THREE.Bone
    l_hipPiston_K_0156: THREE.Bone
    l_hipPiston_L_0157: THREE.Bone
    l_hipPiston_M_0158: THREE.Bone
    l_hipPiston_N_0159: THREE.Bone
    l_hipPiston_O_0160: THREE.Bone
    l_hipPiston_P_0161: THREE.Bone
    r_hipPiston_A_0162: THREE.Bone
    r_hipPiston_B_0163: THREE.Bone
    r_hipPiston_C_0164: THREE.Bone
    r_hipPiston_D_0165: THREE.Bone
    r_hipPiston_E_0166: THREE.Bone
    r_hipPiston_F_0167: THREE.Bone
    r_hipPiston_G_0168: THREE.Bone
    r_hipPiston_H_0169: THREE.Bone
    r_hipPiston_I_0170: THREE.Bone
    r_hipPiston_J_0171: THREE.Bone
    r_hipPiston_K_0172: THREE.Bone
    r_hipPiston_L_0173: THREE.Bone
    r_hipPiston_M_0174: THREE.Bone
    r_hipPiston_N_0175: THREE.Bone
    r_hipPiston_O_0176: THREE.Bone
    r_hipPiston_P_0177: THREE.Bone
    ref_0178: THREE.Bone
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Head: THREE.MeshStandardMaterial
    Misc: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/droide.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // State for movement
  const [target, setTarget] = React.useState<THREE.Vector3 | null>(null)
  const [isWeb, setIsWeb] = React.useState(false)

  React.useEffect(() => {
    setIsWeb(true)
  }, [])

  useFrame((state) => {
    if (!group.current || !isWeb) return

    // Raycast to find mouse intersection with ground plane (y=0)
    state.raycaster.setFromCamera(state.mouse, state.camera)
    const intersects = state.raycaster.intersectObjects(state.scene.children, true)

    // Filter for the invisible ground plane we added (or just any plane)
    // For simplicity, we can also mathematically project the mouse to y=0 since our camera is known
    // But raycasting the ground plane (added in RobotFace) is safer.
    // Let's assume the invisible plane is the first mesh hit that is roughly flat at y=0.

    // We actually just want to set the target where the mouse is on the floor.
    const groundHit = intersects.find(hit => hit.object.type === 'Mesh' && Math.abs(hit.point.y) < 0.1)

    if (groundHit) {
      setTarget(groundHit.point)
    }

    if (target) {
      const position = group.current.position
      const direction = new THREE.Vector3().subVectors(target, position)
      const distance = direction.length()

      if (distance > 0.5) {
        direction.normalize()

        const speed = 0.02
        position.add(direction.multiplyScalar(speed))

        const lookTarget = new THREE.Vector3(target.x, position.y, target.z)
        group.current.lookAt(lookTarget)

        const action = actions['motion']
        if (action && !action.isRunning()) {
          action.reset().fadeIn(0.5).play()
        }
      } else {
        const action = actions['motion']
        if (action && action.isRunning()) {
          action.fadeOut(0.5)
        }
      }
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[1.571, 0, 0]} scale={1.442}>
          <group name="f95ba1337bf34cbaa688b750654cb3acfbx" rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="Droide_de_seguridad_Star_Wars_KX" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Body} skeleton={nodes.Object_7.skeleton} morphTargetDictionary={nodes.Object_7.morphTargetDictionary} morphTargetInfluences={nodes.Object_7.morphTargetInfluences} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Head} skeleton={nodes.Object_8.skeleton} morphTargetDictionary={nodes.Object_8.morphTargetDictionary} morphTargetInfluences={nodes.Object_8.morphTargetInfluences} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Misc} skeleton={nodes.Object_9.skeleton} morphTargetDictionary={nodes.Object_9.morphTargetDictionary} morphTargetInfluences={nodes.Object_9.morphTargetInfluences} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/droide.glb')
